#!/bin/bash
# Completely remove a file from a git repository history
#
# Copyleft 2017 by Ignacio Nunez Hernanz <nacho _a_t_ ownyourbits _d_o_t_ com>
# GPL licensed (see end of file) * Use at your own risk!
#
# Usage:
#   git-forget-blob file_to_forget
#
# Notes:
#   It rewrites history, therefore will change commit references and delete tags

function git-forget-blob()
{
  git repack -A
  ls .git/objects/pack/*.idx &>/dev/null || {
    echo "there is nothing to be forgotten in this repo" && return;
  }
  local BLOBS=( $( git verify-pack -v .git/objects/pack/*.idx | grep blob | awk '{ print $1 }' ) )
  for ref in ${BLOBS[@]}; do
    local FILE="$( git rev-list --objects --all | grep $ref | awk '{ print $2 }' )"
    [[ "$FILE" == "$1" ]] && break
    unset FILE
  done
  [[ "$FILE" == "" ]] && { echo "$1 not found in repo history" && return; }
 
  git tag | xargs git tag -d
  git filter-branch --index-filter "git rm --cached --ignore-unmatch $FILE"
  rm -rf .git/refs/original/ .git/refs/remotes/ .git/*_HEAD .git/logs/
  git for-each-ref --format="%(refname)" refs/original/ | \
    xargs -n1 --no-run-if-empty git update-ref -d
  git reflog expire --expire-unreachable=now --all
  git repack -A -d
  git prune
}

git-forget-blob $@

